Revert "Deprecate OpenSL ES for Android as of API level 30 (R)"
This reverts commit 7fad29e9b6638ca648f1c1001a8dcfec49779969.

Reason for revert:

vendor/unbundled_google/libs/ndk_translation/android_api/libOpenSLES/sles_trampolines.cc:1044:21: error: 'slCreateEngine' is deprecated: first deprecated in Android 30 [-Werror,-Wdeprecated-declarations]
SLresult result = slCreateEngine(
^
frameworks/wilhelm/include/SLES/OpenSLES.h:2752:28: note: 'slCreateEngine' has been explicitly marked deprecated here
SL_API SLresult SLAPIENTRY slCreateEngine(
^
1 error generated.

Change-Id: I54c4c1a34c54ceaa9af512331554ecbb52ac0741